language: php
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^(bugfix|feature)\/.*$/

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - secure: "IEmCQNLHz63zsgcaVVbbeJDZ/Ayx58iJebr5zKDUN/Cbb5MZyW8WgQ5VIn3hlnJsPZrYLx0h3PPSqOB2qLKa02VQaljC50edjSVqT3UsIyC7S+xFA0Vnz492Lf6QFjO6ZiCOqtDiY4fPjOF16nyQO46V2tx4+2W7qVuGy6QHGZw="
    - DB=mysql
  matrix:
    - SCRIPT_JOB="PHP-CS-FIXER"
    - SCRIPT_JOB="BUILDSH"
    - SCRIPT_JOB="BASH-AUTOCOMPLETION"
    - MAGENTO_VERSION="magento-ce-2.2.0" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.9" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.8" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.7" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.6" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.5" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.4" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.3" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.2" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.1" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.1.0" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.16" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.15" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.14" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.13" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.12" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.11" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.10" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.9" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.8" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.7" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.6" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.5" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.4" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.2" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.1" INSTALL_SAMPLE_DATA=0
    - MAGENTO_VERSION="magento-ce-2.0.0" INSTALL_SAMPLE_DATA=0

matrix:
  fast_finish: true
  exclude:
    # Newer Magento versions uses newer PHP versions
    - php: 5.6
      env: MAGENTO_VERSION="magento-ce-2.2.0" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.2.0" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.9" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.8" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.7" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.6" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.5" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.4" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.3" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.2" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.1" INSTALL_SAMPLE_DATA=0
    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-2.1.0" INSTALL_SAMPLE_DATA=0
  include:
    # Lint PHP code with future PHP versions (forward compatibility)
    - php: 7.0
      env: SCRIPT_JOB=LINTSH
      script: find {src,tests} -name "*.php" ! -path '*/String.php' -print0 | xargs
        -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1
    - php: 7.1
      env: SCRIPT_JOB=LINTSH
      script: find {src,tests} -name "*.php" ! -path '*/String.php' -print0 | xargs
        -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1
    # Run the cs-fixer and build script with different PHP versions
    - php: 7.1
      env: SCRIPT_JOB="PHP-CS-FIXER"
    - php: 7.1
      env: SCRIPT_JOB="BUILDSH"
    - php: 7.1
      env: SCRIPT_JOB="BASH-AUTOCOMPLETION"

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo

install:
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs

before_script:
  - source build/travis/before_script.sh

script:
  - build/travis/script.sh
